
package org.example.controller;

import org.example.model.ApiEndpoint;
import org.example.model.TestCase;
import org.example.model.TestResult;
import org.example.service.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;

import java.util.ArrayList;
import java.util.List;


@RestController
public class TestController {

    @Autowired
    private AiService aiService;
    @Autowired
    private TestExecutor testExecutor;
    @Autowired
    private ReportBuilder reportBuilder;

/*
    @GetMapping("/ai/chat")
    public String chat(@RequestParam String message) {
        // simple call
        return aiService.ask(message);
    }

    @GetMapping("/ai/analyze")
    public String analyze(@RequestParam String code) {
        // call with a system prompt, letting the AI act as a "code review assistant"
        String systemPrompt = "You are a code review expert. Analyze the following Java code snippet, identify potential issues, and suggest improvements.";
        return aiService.askWithSystem(systemPrompt, code);
    }

    @PostMapping("/ai/generate-test")
    public String generateTest(@RequestBody String apiDescription) {
        return aiService.generateTestCasesJson(apiDescription);
    }

    @PostMapping(value = "/ai/generatetext-test", consumes = "text/plain")
    public String generateTestText(@RequestBody String apiDescription) {
        return aiService.generateTestCasesJson(apiDescription);
    }
*/


    @GetMapping("/ai/run-swagger/GetTestCaseWithAIhallucination")
    public String runSwaggerWithAIHallucination() {
        String description = """
        Endpoint: /api/users
        HTTP Method: POST
        Parameters: name (String), age (Integer)""";



        return aiService.generateTestCasesJsonWithAIhallucination(description);
    }

    //Parse swagger.json into ApiEndpoint objects, then assemble the endpoints into a request-body description
    //Use the AI to turn the request-body description into JSON, parse it into TestCase objects, validate the test cases in Java, execute them and generate a report
    //StringBuilder jsonReport = new StringBuilder(); //test cases generated by the AI
    private static final int BATCH_SIZE = 5;
    @PostMapping(value = "/ai/run-swagger")
    public String runSwagger() throws Exception {
        // 1. Parse Swagger and collect all endpoints
        RestClient restClient = RestClient.create();

        String swaggerJson = restClient.get()
                .uri("http://localhost:8080/v3/api-docs")
                .retrieve()
                .body(String.class);

        //guard against markdown characters such as ` being returned
        int jonsStart = 0;
        if (swaggerJson != null) {
            jonsStart = swaggerJson.indexOf('{');
        }
        int jsonEnd = 0;
        if (swaggerJson != null) {
            jsonEnd = swaggerJson.lastIndexOf('}');
        }
        if (jonsStart >= 0 && jsonEnd > jonsStart) {
            swaggerJson = swaggerJson.substring(jonsStart, jsonEnd + 1);
        }


        List<ApiEndpoint> endpoints = aiService.parseSwaggerToEndpoint(swaggerJson);

        // 2. Walk each endpoint and generate test cases
        List<TestCase> allCases = new ArrayList<>();
        //  in batches
        for (int i = 0; i < endpoints.size(); i += BATCH_SIZE) {
            int end = Math.min(i + BATCH_SIZE, endpoints.size());
            List<ApiEndpoint> batch = endpoints.subList(i, end);
            StringBuilder description = new StringBuilder();
            for (ApiEndpoint ep : batch) {
                // Concatenate the endpoint's raw JSON with its path and method into one description
                description.append("Endpoint: ").append(ep.getPath())
                        .append("\nHTTP Method: ").append(ep.getMethod())
                        .append("\nEndpoint Definition: ").append(ep.getRawJson())
                        .append("\nRequest Body Schema: ").append(ep.getSchemaJson())
                        .append("\n\n");


            }
            description.append("Generate two test cases per endpoint path and HTTP method. ")
                    .append("For example, if /test/ supports both POST and GET, generate two cases for each method — one normal case and one exception case. ")
                    .append("If the endpoint is a GET like /api/users that requires no path variable or request parameter, generate only one normal case.\n")
                    .append("For the POST method in this test scenario, the id is set by default, so the requestBody should not include the id field.");
            //no AI timeout check has been added yet
            String json = aiService.generateTestCasesJson(String.valueOf(description));


            //jsonReport = jsonReport.append(json).append("\n");
            List<TestCase> cases = aiService.parseToTestCases(json);
            allCases.addAll(cases);
            Thread.sleep(500);
        }



        // 3. Validate and Execute
         boolean validatedTc;
        List<TestResult> results = new ArrayList<>();
        TestResult result;

        for (TestCase tc : allCases) {
            validatedTc = testExecutor.validateAIhallucination(tc);
            if(!validatedTc)
            {
                results.add(new TestResult(tc, 0, false, "AI hallucination"));
            } else{
                result = testExecutor.executeAndPostVerification(tc);
                results.add(result);
            }
        }

        // 5. Produce the report

        return reportBuilder.build(allCases, results);


    }


}