
package org.example.controller;

import com.fasterxml.jackson.core.JsonProcessingException;
import org.example.model.*;
import org.example.service.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;

import java.util.ArrayList;
import java.util.List;


@RestController
public class TestController {

    @Autowired
    private AiService aiService;
    @Autowired
    private HttpExecutor httpExecutor;
    @Autowired
    private UiExecutor uiExecutor;
    @Autowired
    private ReportBuilder reportBuilder;
    private static final Logger log = LoggerFactory.getLogger(TestController.class);
/*
    @GetMapping("/ai/chat")
    public String chat(@RequestParam String message) {
        // simple call
        return aiService.ask(message);
    }

    @GetMapping("/ai/analyze")
    public String analyze(@RequestParam String code) {
        // call with a system prompt, letting the AI act as a "code review assistant"
        String systemPrompt = "You are a code review expert. Analyze the following Java code snippet, identify potential issues, and suggest improvements.";
        return aiService.askWithSystem(systemPrompt, code);
    }

    @PostMapping("/ai/generate-test")
    public String generateTest(@RequestBody String apiDescription) {
        return aiService.generateTestCasesJson(apiDescription);
    }

    @PostMapping(value = "/ai/generatetext-test", consumes = "text/plain")
    public String generateTestText(@RequestBody String apiDescription) {
        return aiService.generateTestCasesJson(apiDescription);
    }
*/


    @GetMapping("/ai/run-swagger/GetTestCaseWithAIhallucination")
    public String runSwaggerWithAIHallucination() {
        String description = """
        Endpoint: /api/users
        HTTP Method: POST
        Parameters: name (String), age (Integer)""";



        return aiService.generateTestCasesJsonWithAIhallucination(description);
    }

    //Parse swagger.json into ApiEndpoint objects, then assemble the endpoints into a request-body description
    //Use the AI to turn the request-body description into JSON, parse it into TestCase objects, validate the test cases in Java, execute them and generate a report
    //StringBuilder jsonReport = new StringBuilder(); //test cases generated by the AI
    private static final int BATCH_SIZE = 5;
    @PostMapping(value = "/ai/run-swagger")
    public String runSwagger() {
        // 1. Parse Swagger and collect all endpoints
           try {
               RestClient restClient = RestClient.create();

               String swaggerJson = restClient.get()
                       .uri("http://localhost:8080/v3/api-docs")
                       .retrieve()
                       .body(String.class);

               //guard against markdown characters such as ` being returned
               int jonsStart = 0;
               if (swaggerJson != null) {
                   jonsStart = swaggerJson.indexOf('{');
               }
               int jsonEnd = 0;
               if (swaggerJson != null) {
                   jsonEnd = swaggerJson.lastIndexOf('}');
               }
               if (jonsStart >= 0 && jsonEnd > jonsStart) {
                   swaggerJson = swaggerJson.substring(jonsStart, jsonEnd + 1);
               }


               List<ApiEndpoint> endpoints = aiService.parseSwaggerToEndpoint(swaggerJson);

               // 2. Walk each endpoint and generate test cases
               List<TestCase> allCases = new ArrayList<>();
               //  in batches
               for (int i = 0; i < endpoints.size(); i += BATCH_SIZE) {
                   int end = Math.min(i + BATCH_SIZE, endpoints.size());
                   List<ApiEndpoint> batch = endpoints.subList(i, end);
                   StringBuilder description = new StringBuilder();
                   for (ApiEndpoint ep : batch) {
                       // Concatenate the endpoint's raw JSON with its path and method into one description
                       description.append("Endpoint: ").append(ep.getPath())
                               .append("\nHTTP Method: ").append(ep.getMethod())
                               .append("\nEndpoint Definition: ").append(ep.getRawJson())
                               .append("\nRequest Body Schema: ").append(ep.getSchemaJson())
                               .append("\n\n");


                   }
                   description.append("Generate two test cases per endpoint path and HTTP method. ")
                           .append("For example, if /test/ supports both POST and GET, generate two cases for each method — one normal case and one exception case. ")
                           .append("If the endpoint is a GET like /api/users that requires no path variable or request parameter, generate only one normal case.\n")
                           .append("For the POST method in this test scenario, the id is set by default, so the requestBody should not include the id field.");
                   //no AI timeout check has been added yet
                   String json = aiService.generateTestCasesJson(String.valueOf(description));
                   //String json = aiService.generateTestCasesJsonWithAIhallucination(String.valueOf(description));
                   log.info("AI returned JSON: {}", json);

                   //jsonReport = jsonReport.append(json).append("\n");
                   List<TestCase> cases;
                   try {
                       cases = aiService.parseToTestCases(json);
                   } catch (JsonProcessingException e) {
                       // Parse to Json exception, return the json and error to the caller
                       return "Failed to parse AI output.\nAI returned JSON:\n" + json + "\nError: " + e.getMessage();
                   }
                   log.info("Parsed {} cases", cases.size());
                   allCases.addAll(cases);
                   Thread.sleep(500);
               }


               // 3. Validate and Execute
               boolean validatedTc;
               List<TestResult> results = new ArrayList<>();
               TestResult result;
               List<HallucinationRecord> hallucinations = new ArrayList<>();

               for (TestCase tc : allCases) {
                   HallucinationValidationResult vr = httpExecutor.validateAIhallucination(tc);
                   if (!vr.isValid()) {
                       hallucinations.add(new HallucinationRecord(tc, vr.getType(), vr.getReason()));
                       results.add(new TestResult(tc, 0, false, "AI hallucination: " + vr.getReason()));
                   } else {
                       result = httpExecutor.executeAndPostVerification(tc);
                       results.add(result);
                   }
               }

               // 5. Produce the report

               return reportBuilder.build(allCases, results, hallucinations);
           }
           catch (Exception e) {
            log.error("runSwagger failed", e);
            return "runSwagger failed: " + e.getMessage();
        }

    }

    @PostMapping("/ai/run-ui-test")
    public String runUiTest(@RequestBody String pageDescription) throws Exception {



        // 1. AI generate json scenarios
        String json = aiService.generateUiScenariosJson(pageDescription);
        log.info("AI returned JSON: {}", json);
        // 2. parse
        List<UiScenario> scenarios = aiService.parseToUiScenarios(json);

        // 3. execution
        List<TestResult> results = uiExecutor.executeScenarios(scenarios);


        // 4. Get TestCase from results
        List<TestCase> allCases = new ArrayList<>();
        for (TestResult r : results) {
            allCases.add(r.getTestCase());
        }

        return reportBuilder.build(allCases, results, new ArrayList<>());
    }

}